io:
  NRRD_folder_path: '/mnt/data6/DeepPY/ai_lung_damage/data/nrrd/'
  lung_segmentation_folder_path: '/mnt/data6/DeepPY/ai_lung_damage/data/lung_seg/'

preprocessing:
  CUDA_VISIBLE_DEVICES: "1"
  NUMEXPR_MAX_THREADS: "32"