# input NRRD folder and lung segmentation output folder
io:
  NRRD_folder_path: '/mnt/data/test/'
  lung_segmentation_folder_path: '/mnt/data/lung_seg_out/'

preprocessing:
  CUDA_VISIBLE_DEVICES: "1"
  NUMEXPR_MAX_THREADS: "32"