io:
  # folder should contain numpy array of extracted lungs
  path_to_data_folder_testing: '/mnt/data6/DeepPY/ai_lung_damage/data/test/'

  csv_path_to_save_lung_health_scores: '/mnt/data6/DeepPY/src_main/CSVs/test_try'   

  # subdir under which the network weights should be saved
  model_weight_url_to_download: "https://zenodo.org/records/14065852/files/AI_Lung_Health_Model.pth"

  device_cuda: 'cuda:0'


 # hyperparameters used during the training of AI Lung Health / Dont change during testing

training:
    
  conv_dropout: 0.2

  FC_dropout: 0.4
    
  batch_size: 16
   
  normalization_value_min: -1024

  normalization_value_max: 1566

testing:

  batch_size: 1

