io:
  # root path to data
  path_to_data_folder_training: '/mnt/lungscore/data/train/'
  path_to_data_folder_tuning: '/mnt/lungscore/data/tune/'

  # csv with data file name and label
  path_to_csv_training: '/mnt/lungscore/labels/train_dataset.csv'
  path_to_csv_tuning: '/mnt/lungscore/labels/tune_dataset.csv'
  
  # subdir under which the network weights should be saved
  model_weights_foldertosave_name: '/mnt/lungscore/model_weights/'


 # hyperparameters used during the training of AI Lung Health
training:
    
  conv_dropout: 0.2

  FC_dropout: 0.4
    
  batch_size: 16
    
  num_epochs: 1000
    
  lr: 0.0003
   
  normalization_value_min: -1024

  normalization_value_max: 1566

tuning:

  batch_size: 1

wandb:

  splits of classes: 'Q1_Packyears_without_chronicfindings_VS_Q4_Packyears'

  normalization_method: "Normalize_by_10%and90%_from_training_set"

  normalization_values: [-1024,1566]

  Aim: 'AI-derived Lung Score'

